version: '2'
services:
    mongo-router:
        container_name: "mongo-router"
        image: mongo
        ports:
            - "30031:27017"
        depends_on:
            - "mongo-cnf-1"
            - "mongo-1-1"
            - "mongo-2-1"
        links:
            - mongo-cnf-1:mongo-cnf-1
            - mongo-cnf-2:mongo-cnf-2
            - mongo-cnf-3:mongo-cnf-3
            - mongo-1-1:mongo-1-1
            - mongo-1-2:mongo-1-2
            - mongo-1-3:mongo-1-3
            - mongo-2-1:mongo-2-1
            - mongo-2-2:mongo-2-2
            - mongo-2-3:mongo-2-3
        command: mongos --configdb cnf-serv/mongo-cnf-1:27017,mongo-cnf-2:27017,mongo-cnf-3:27017
        restart: always

    mongo-shard-setup:
        image: mongo
        depends_on:
            - "mongo-router"
        links:
            - mongo-router:mongo-router
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGOS=mongo-router
            - MONGO11=mongo-1-1
            - MONGO12=mongo-1-2
            - MONGO13=mongo-1-3
            - MONGO21=mongo-2-1
            - MONGO22=mongo-2-2
            - MONGO33=mongo-2-3
            - RS1=rs1
            - RS2=rs2
            - PORT=27017
            - PORT1=27017
            - PORT2=27017
            - PORT3=27017
        entrypoint: [ "/scripts/init_shard.sh" ]
